### PR TITLE
Fixing issue where newline cause errors in Markdown files while rende…

### PR DESCRIPTION
**Pull request by jaygurnani**
…ring

## Errors while rendering
Some markdown engines have errors when trying to render html tables that have new lines in them. Specfically, new lines in <td> element cause an issue By removing them we are fixing this issue. @exogen Are you the right person to review this?

### CODE REVIEW

**Comment by exogen** [comment]
To my knowledge, this would break the rendering in Github Flavored Markdown, but I haven't tested it yet.

Historically at least, GFM requires the newlines in order to treat the HTML content as Markdown again (vs. raw HTML).

e.g.

```html
<td>
some content here <-- not parsed as Markdown
</td>
```

```html
<td>

some content here <-- parsed as Markdown

</td>
```

Will have to look into whether this is still the case. What Markdown engines is it a problem for?

**Comment by exogen** [comment]
> To my knowledge, this would break the rendering in Github Flavored Markdown, but I haven't tested it yet.

Looks like this is still the case – see this example: https://gist.github.com/exogen/2db509b6926f672225a58c4aa21b7829

Perhaps we could add an option to support different Markdown engines?

**Comment by jaygurnani** [comment]
> Perhaps we could add an option to support different Markdown engines?

Yeah I am happy with this approach. The markdown rendering engine I am using is [blackfriday](https://github.com/russross/blackfriday) which is being wrapped around by another rendering engine called [Hugo](https://gohugo.io/content-management/shortcodes/)

Unfortunately there is no easy way to show you the error you get since there are quite a few layers involved, but from the documentation of blackfriday, you can see explicitly that elements inside `<td>` do not have a newline separator - see here https://github.com/russross/blackfriday/blob/master/testdata/Markdown%20Documentation%20-%20Syntax.text line 102 

OR 

https://test-staticman.netlify.app/archive/content-organisation/blackfriday-markdown/ here for a rendered version of the syntax guide.

A new line character in between the `<td>` simply causes the web server to return a 500, while removing the new line character allows the markdown engine to render correctly.

**Comment by exogen** [comment]
> Note that Markdown formatting syntax is not processed within block-level
HTML tags. E.g., you can't use Markdown-style `*emphasis*` inside an
HTML block.

What should happen to the field & argument descriptions in this case? Let's say someone does put a newline or other Markdown in their argument or field description, would they just not be able to use this output mode and keep that limitation in mind? A couple other options would be to render their Markdown for them (so it gets turned into HTML and thus can be stuck in the `<td>`, or strip Markdown formatting from it to force it to text only – but both of those involve adding a Markdown renderer as a dependency, which I'd like to avoid. (One nice property of the current setup is that we just stick their Markdown into the template literally, there's no need to actually process it.)

**Comment by exogen** [comment]
Maybe the most flexible would be to have a hook where they could supply a function to process the Markdown content however they'd like? Then the default could be what happens now – the `\n${field.description}\n` behavior – but if they want to either strip certain characters or syntax, or render it with their Markdown renderer of choice into HTML, they could do that?

**Comment by jaygurnani** [comment]
> Maybe the most flexible would be to have a hook where they could supply a function to process the Markdown content however they'd like? Then the default could be what happens now – the `\n${field.description}\n` behavior – but if they want to either strip certain characters or syntax, or render it with their Markdown renderer of choice into HTML, they could do that?

Yeah, this approach works as well.

**Comment by exogen** [comment]
Closing this solution since it breaks GitHub Flavored Markdown, but open to the custom preprocessor in another PR!

**Pull request closed without merging**
