### PR TITLE
Support for Input Objects

### PR DESCRIPTION
**Pull request by thomasmichaelwallace**
Really enjoying using this package- but I noticed you didn't support GraphQLInputObjects, so I've taken a stab at it!

### CODE REVIEW

**Comment by exogen** [comment]
Awesome, I'll be able to check this out when I'm back from vacation in a couple days. Thanks!

**Comment by thomasmichaelwallace** [comment]
The tests fail- but I think that's because the snapshots are out-of-date... suggestions welcome :)

**Comment by exogen** [comment]
I just now finished improving the test suite quite a bit and migrating it to Jest, in #35.

If you rebase this onto master, the tests should be fixed, and you can hopefully spot a good place to add a test schema demonstrating the Input Object support!

**Comment by exogen** [comment]
Input rendering looks good, thanks for the PR!

**Comment by exogen** [comment]
Released in v5.0.0!

**Comment by thomasmichaelwallace** [comment]
Hi!

Thanks for accepting; yes, as you'd spotted my master branch was a few more commits ahead from this PR as I'm playing with _implements_ for interfaces and trying to get our new lines in descriptions to work properly.

**Comment by exogen** [comment]
Ah, sorry if I messed up what was in your `master`, the additions were making their way into this PR as well so I had to separate 'em out.

**Comment by thomasmichaelwallace** [comment]
No worries.

I'll take a look at doing interfaces properly some time!

**Pull request merged**
