### PR TITLE
Move graphql to peerDependencies

### PR DESCRIPTION
**Pull request by exogen**

### CODE REVIEW

**Comment by johannespfeiffer** [comment]
How does this work with `npx` now?

```
npx graphql-markdown https://our-api/graphql
```

returns
```
Cannot find module 'graphql'
```

**Comment by exogen** [comment]
Is the use case for running it with `npx` to use it in a non-Node project (thus no package.json to add it to)?

There were downsides to this package bundling its own `graphql`, like not using the same version that the consuming package is using (in Node projects). But I could consider other workarounds or warning messages for that.

**Comment by johannespfeiffer** [comment]
Yes, we are using it in a bash script for a GitHub action to update our online docs. It was broken 4 days ago. 

Workaround for us now is to use an older version by adding @5.2.0.

**Comment by exogen** [comment]
Ah this is one danger of using `npx` without an explicit version, so I recommend anyone using `npx` in their build scripts to do as you did and always specify the version (not just for this package but for any package). Otherwise it will automatically pull in the latest version and any breaking changes with it – this was a semver-major version bump of graphql-markdown for exactly this reason, it was explicitly a breaking change.

But, it would be nice if it still worked with `npx` so I'll have a look at another release!

**Pull request merged**
